export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>

        <header style={{backgroundColor: "#ff6900", padding: "1rem"}}>
          <h4>This is the header</h4>
        </header>

        {children}

        <footer style={{backgroundColor: "#333", padding: "1rem", color: "#fff"}}>
          <h5>This is the footer</h5>
        </footer>

      </body>
    </html>
  )
}
